### ISSUE TITLE
seeded data is not showing in the view or Postman

### ISSUE THREAD

**Issue by savageblackout** [savageblackout/our_restroom#1]
I am working on the following User Story:
"As a user, I want to see a list of businesses that have been added to the database."

The error I get is:
angular.js:10661 POST http://localhost:3000/api/businesses/:id 404 (Not Found)(anonymous function) @ angular.js:10661sendReq @ angular.js:10480serverRequest @ angular.js:10187processQueue @ angular.js:14634(anonymous function) @ angular.js:14650Scope.$eval @ angular.js:15878Scope.$digest @ angular.js:15689Scope.$apply @ angular.js:15986(anonymous function) @ angular.js:23376m.event.dispatch @ jquery.js:4670r.handle @ jquery.js:4338
angular.js:12416 Error: Object {data: "Not Found", status: 404, config: Object, statusText: "Not Found"}

I have attempted to address the issue by:
creating a seed file and running node config/seeds.js --> this results in an empty index page.

**Comment by jim-clark** [comment]
It's working now :)
